# Servidor
server.port=8080

# Groq (usa el cliente OpenAI de Spring AI)
spring.ai.openai.api-key= GROQ_API_KEY
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama3-8b-8192

# Embeddings (modelo local gratuito)
spring.ai.openai.embedding.base-url=https://api.groq.com/openai
spring.ai.openai.embedding.api-key=TU_API_KEY_DE_GROQ
spring.ai.openai.embedding.options.model=llama3-8b-8192

# ChromaDB
spring.ai.vectorstore.chroma.client.host=localhost
spring.ai.vectorstore.chroma.client.port=8000
spring.ai.vectorstore.chroma.collection-name=secretaria-virtual

# CORS
allowed.origins=*
